//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "event_object")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub object_type: String,
    pub event_id: Uuid,
    pub section_id: Option<Uuid>,
    pub label: Option<String>,
    pub is_enable: bool,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: HasOne<super::event::Entity>,
    #[sea_orm(has_many)]
    pub event_object_positions: HasMany<super::event_object_position::Entity>,
    #[sea_orm(has_many)]
    pub reservation_items: HasMany<super::reservation_item::Entity>,
    #[sea_orm(
        belongs_to,
        from = "section_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub section: HasOne<super::section::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
