//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "event_object_position")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_object_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub position_x: f64,
    #[sea_orm(column_type = "Double")]
    pub position_y: f64,
    #[sea_orm(column_type = "Double")]
    pub rotation: f64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_object::Entity",
        from = "Column::EventObjectId",
        to = "super::event_object::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    EventObject,
}

impl Related<super::event_object::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventObject.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
