//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "form")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub schema: Option<Json>,
    pub settings: Option<Json>,
    pub title: Option<String>,
    pub description: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: HasOne<super::event::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
