//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::account::Entity as Account;
pub use super::seat::Entity as Seat;
pub use super::session::Entity as Session;
pub use super::user::Entity as User;
pub use super::verification::Entity as Verification;
pub use super::workspace::Entity as Workspace;
pub use super::workspace_object::Entity as WorkspaceObject;
