//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reservation_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub reservation_id: Uuid,
    pub event_object_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub price_at_booking: f64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "event_object_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event_object: HasOne<super::event_object::Entity>,
    #[sea_orm(
        belongs_to,
        from = "reservation_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub reservation: HasOne<super::reservation::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
