//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reservation_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub reservation_id: Uuid,
    pub event_object_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub price_at_booking: f64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event_object::Entity",
        from = "Column::EventObjectId",
        to = "super::event_object::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    EventObject,
    #[sea_orm(
        belongs_to = "super::reservation::Entity",
        from = "Column::ReservationId",
        to = "super::reservation::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Reservation,
}

impl Related<super::event_object::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventObject.def()
    }
}

impl Related<super::reservation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reservation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
