//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "reservation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: String,
    pub event_id: Uuid,
    pub status: String,
    #[sea_orm(column_type = "Double")]
    pub total_price: f64,
    pub expires_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub approved_by: Option<String>,
    pub approved_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: HasOne<super::event::Entity>,
    #[sea_orm(has_many)]
    pub reservation_items: HasMany<super::reservation_item::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User2",
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub user_2: HasOne<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User1",
        from = "approved_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub user_1: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
