//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "section")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub event_id: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "event_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub event: HasOne<super::event::Entity>,
    #[sea_orm(has_many)]
    pub event_objects: HasMany<super::event_object::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
