//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub email_verified: bool,
    pub image: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(has_many)]
    pub accounts: HasMany<super::account::Entity>,
    #[sea_orm(has_many)]
    pub forms: HasMany<super::form::Entity>,
    #[sea_orm(has_many)]
    pub form_submissions: HasMany<super::form_submission::Entity>,
    #[sea_orm(has_many)]
    pub reservations: HasMany<super::reservation::Entity>,
    #[sea_orm(has_many)]
    pub sessions: HasMany<super::session::Entity>,
    #[sea_orm(has_many)]
    pub workspaces: HasMany<super::workspace::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
