//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "workspace_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub workspace_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub invited_by: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub updated_at: DateTime,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        relation_enum = "User2",
        from = "invited_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user_2: HasOne<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "User1",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub user_1: HasOne<super::user::Entity>,
    #[sea_orm(
        belongs_to,
        from = "workspace_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspace: HasOne<super::workspace::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
